name: build & push Docker image

on:
  pull_request:
    branches:
      - master
    types: [ closed ]

permissions:
  contents: write

jobs:
  build_and_push:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build
        uses: spring-io/spring-gradle-build-action@v2
        with:
          java-version: 25
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Config git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Create tag
        run: |
          ./gradlew semver -x test -x check --patch
      - name: Get tag version
        id: generate_tag
        run: |
          tag=$(cat gradle.properties  | grep "version" | cut -d "=" -f 2)
          echo "TAG=$tag" >> $GITHUB_OUTPUT
        shell: bash
      - name: Set new tag version to HELM files
        run: |
          yq -i '.image.tag = "${{ steps.generate_tag.outputs.TAG }}"' ${{ github.workspace }}/helm/example/values.yaml
          yq -i '.version = "${{ steps.generate_tag.outputs.TAG }}"' ${{ github.workspace }}/helm/example/Chart.yaml
          yq -i '.appVersion = "${{ steps.generate_tag.outputs.TAG }}"' ${{ github.workspace }}/helm/example/Chart.yaml
          
          git add .
          git commit -m "Change version in HELM files to ${{ steps.generate_tag.outputs.TAG }}"
          
          git push origin master
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mvc:${{ steps.generate_tag.outputs.TAG }}